### ISSUE TITLE
move lsof man page to section 1

### ISSUE THREAD

**Issue by pschiffe** [masatake/lsof-linux#9]
Hi Masatake,

based on [1], lsof was moved to the `/usr/bin` directory in Fedora (and multiple other distros have it there instead of `/usr/sbin`), therefore lsof man page belongs to the section 1 instead of 8. In Fedora, this is done by patch [2] and during the installation [3]. Please, consider this change for this repo as well. Thanks.

peter

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1260300
[2] https://src.fedoraproject.org/rpms/lsof/blob/master/f/lsof-man-page-section.patch
[3] https://src.fedoraproject.org/rpms/lsof/blob/master/f/lsof.spec#_47

**Comment by masatake** [comment]
If you are o.k., please make a pull request and merge by yourself.

**Comment by masatake** [comment]
I decided not to port this change to "lsof" repository because it seems that root privileged is needed to run lsof on FreeBSD.
